### ISSUE TITLE
db_setup.sh and index.py files missing

### ISSUE THREAD

**Issue by datacrud8** [itsyaasir/pdf-embedding-indexer#1]
Hi, thanks for the sharing this app.
I'm trying to build this in local but bash db_setup.sh and index.py files are missing the project.
Can you able to share those files. Thank you.

**Comment by itsyaasir** [comment]
Yeah, sorry about that, let me share the files in a few.

**Comment by datacrud8** [comment]
sure thank you. If you can please share.

**Comment by itsyaasir** [comment]
Updated the files, they were not actually missing, just forgot to update the README files

**Comment by itsyaasir** [comment]
Make sure to use compatible model with the llama-cpp-python

**Comment by datacrud8** [comment]
great thanks. do you have any plane to build client side UI? this is only CLI.

now requirements.txt missed here.

**Comment by itsyaasir** [comment]
Hey, use the script to initialize the environment, it uses conda, so make sure you have conda installed.

use ‘setup_conda.sh’ script and activate the environment afterwards
